spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: Giahuy1007*
  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate
    show-sql: true
  mvc:
    validation:
      fail-fast: true